#!/bin/bash

set -e
# Enable this to debug
# set -x
BW_SESSION_FILE_PATH=~/.con

# Retrieve previously saved BW_SESSION
if [ -e $BW_SESSION_FILE_PATH ]; then
	export BW_SESSION="$(cat $BW_SESSION_FILE_PATH)"
else
	echo "File $BW_SESSION_FILE_PATH doesn't exist" >&2
fi

# Get BW status
bw_status=$(bw status | jq .status)

if [ $bw_status = '"unauthenticated"' ]; then
	BW_SESSION=$(bw login --raw)
elif [ $bw_status = '"locked"' ]; then
	BW_SESSION=$(bw unlock --raw)
elif [ $bw_status = '"unlocked"' ]; then
	: #Just pass
else
	echo "Unsupported Bitwarden status: $bw_status" >&2
	exit 1
fi

# Get list of active devices that have primary IP address
ip_address="$(nbcli filter device has_primary_ip=True status=active --dl --cols name primary_ip | fzf | cut -w -f 2 | cut -d "/" -f 1)"

# Get names of all credentials from Bitwarden
password_name=$(bw list items | jq '.[].name' | fzf | tr -d '"')

# Get password from Bitwarden
password=$(bw get password "$password_name")

# Connect to device using password
SSHPASS=$password sshpass -e ssh -J noc $ip_address

